---
- hosts: all
  become: true
  tasks:
    - name: Installing the Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: index.html,login.html,main.css,java.js,bg.jpg,css.png,html.png,image.png,js.png,python.png
      ansible.builtin.copy:
        src:  /home/patel/My-Portfolio
        dest: /var/www/html
        owner: root
        group: root
        mode: '0777'
